Check if script file exists

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -5,6 +5,12 @@ if [[ -z $1 ]] ; then
 	exit 1
 fi
 
+SCRIPT="/scripts/$1"
+if [[ ! -r $SCRIPT ]] ; then
+	echo "Error: file '$SCRIPT' is not readable"
+	exit 1
+fi
+
 echo Preparing docker container...
 echo
 
@@ -22,7 +28,7 @@ tmux split-window -h
 tmux resize-pane -t 0:0.1 -D 4
 tmux resize-pane -t 0:0.1 -R 10
 
-cp "/scripts/$1" /tmp/testenv_script.yml
+cp "$SCRIPT" /tmp/testenv_script.yml
 
 tmux send-keys -t 0:0.1 '/bin/perl /scripts/controller ; sleep 5 ; tmux kill-session' Enter
 tmux send-keys -t 0:0.2 '/bin/perl /scripts/show-status' Enter
