Yml file as parameter
So it's even more flexible.

Example execution so far:
`asciinema rec -c "docker run -it --rm -v $PWD:/scripts ubuntu /bin/bash /scripts/run-tests travel-status-de-iris_git.yml" recording.cast`

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [[ -z $1 ]] ; then
+	echo "Error: missing parameter (yml file)"
+	exit 1
+fi
+
 echo Preparing docker container...
 echo
 
@@ -17,7 +22,7 @@ tmux split-window -h
 tmux resize-pane -t 0:0.1 -D 4
 tmux resize-pane -t 0:0.1 -R 10
 
-cp /scripts/travel-status-de-iris_git.yml /tmp/testenv_script.yml
+cp "/scripts/$1" /tmp/testenv_script.yml
 
 tmux send-keys -t 0:0.1 '/bin/perl /scripts/controller ; sleep 5 ; tmux kill-session' Enter
 tmux send-keys -t 0:0.2 '/bin/perl /scripts/show-status' Enter
