Check for actions.yml file

diff --git a/run-screencast b/run-screencast
--- a/run-screencast
+++ b/run-screencast
@@ -7,4 +7,9 @@ if [[ ! -d $1 ]] ; then
     exit 1
 fi
 
+if [[ ! -e $1/actions.yml ]] ; then
+    echo "Error: No file named '$1/actions.yml'"
+    exit 1
+fi
+
 tmux new-session "perl ./run-screencast-helper $1"
